dataset:
  type: 'kitti'
  data_dir: 'data/KITTI3D'
  root_dir: ''
  dense_depth_dir: ''
  label_dir: ''
  eval_cls: ['Car']
#  eval_cls: ['Car','Pedestrian','Cyclist']
  batch_size: 16
  num_workers: 4
  class_merging: False
  use_dontcare: False
  use_3d_center: True
  writelist: ['Car','Pedestrian','Cyclist']
  random_flip: 0.5
  random_crop: 0.5
  scale: 0.4
  shift: 0.1
  drop_last_val: True

model:
  type: 'distill'
  backbone: 'dla34'
  neck: 'DLAUp'
  kd_type: ['dlaup_kd', 'affinity_kd', 'head_kd', 'align_freq_kd']

optimizer:
  type: 'adam'
  lr: 0.0005
  weight_decay: 0.00001

lr_scheduler:
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  decay_list: [90, 120, 150]

trainer:
  max_epoch: 200
  eval_start: 90
  eval_frequency: 5 # evaluation interval (in epoch)
  save_frequency: 5 # checkpoint save interval (in epoch)
  disp_frequency: 50 # display interval (in batch)
  log_dir: 'kitti_models/logs/monoafkd'
  out_dir: 'kitti_models/output/monoafkd'
  pretrain_model: {'rgb':'student.pth', 'depth':'teacher.pth'}

tester:
  threshold: 0.2  # confidence filter
  out_dir: ''
  resume_model: '' # pre-trained model path
